package com.overture.questdroid.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class user {

    private Long id;
    private long ID;
    /** Not-null value. */
    private String username;
    private String Avatarurl;
    private Long coin;

    public user() {
    }

    public user(Long id) {
        this.id = id;
    }

    public user(Long id, long ID, String username, String Avatarurl, Long coin) {
        this.id = id;
        this.ID = ID;
        this.username = username;
        this.Avatarurl = Avatarurl;
        this.coin = coin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getAvatarurl() {
        return Avatarurl;
    }

    public void setAvatarurl(String Avatarurl) {
        this.Avatarurl = Avatarurl;
    }

    public Long getCoin() {
        return coin;
    }

    public void setCoin(Long coin) {
        this.coin = coin;
    }

}
